services:
  deklassiert:
    build: .
    container_name: deklassiert
    ports:
      - "8081:8081"
    env_file:
      - .env
    volumes:
      - ./data:/usr/local/app/data
    restart: unless-stopped